// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEz4gop4gjHDOvTxvz9WNu_BEM6NDrpVw',
    appId: '1:243886791249:web:6c1fb298c5921d139ff670',
    messagingSenderId: '243886791249',
    projectId: 'medrandachattiemporeal',
    authDomain: 'medrandachattiemporeal.firebaseapp.com',
    databaseURL: 'https://medrandachattiemporeal-default-rtdb.firebaseio.com',
    storageBucket: 'medrandachattiemporeal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPu4hBt_FSTetXbdSnoJNgnyNxP2KHUu8',
    appId: '1:243886791249:android:a09ec339d0eec0669ff670',
    messagingSenderId: '243886791249',
    projectId: 'medrandachattiemporeal',
    databaseURL: 'https://medrandachattiemporeal-default-rtdb.firebaseio.com',
    storageBucket: 'medrandachattiemporeal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvkubywg5sbPHPNr3LkLeNY3AhFhHihw',
    appId: '1:243886791249:ios:cb7b745119cf43689ff670',
    messagingSenderId: '243886791249',
    projectId: 'medrandachattiemporeal',
    databaseURL: 'https://medrandachattiemporeal-default-rtdb.firebaseio.com',
    storageBucket: 'medrandachattiemporeal.firebasestorage.app',
    iosBundleId: 'com.example.u3t2ChatTiempoReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvkubywg5sbPHPNr3LkLeNY3AhFhHihw',
    appId: '1:243886791249:ios:cb7b745119cf43689ff670',
    messagingSenderId: '243886791249',
    projectId: 'medrandachattiemporeal',
    databaseURL: 'https://medrandachattiemporeal-default-rtdb.firebaseio.com',
    storageBucket: 'medrandachattiemporeal.firebasestorage.app',
    iosBundleId: 'com.example.u3t2ChatTiempoReal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEz4gop4gjHDOvTxvz9WNu_BEM6NDrpVw',
    appId: '1:243886791249:web:c07baec926b4aeae9ff670',
    messagingSenderId: '243886791249',
    projectId: 'medrandachattiemporeal',
    authDomain: 'medrandachattiemporeal.firebaseapp.com',
    databaseURL: 'https://medrandachattiemporeal-default-rtdb.firebaseio.com',
    storageBucket: 'medrandachattiemporeal.firebasestorage.app',
  );

}